name: web测试

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 更新步数
      run: |
        pip install flask flask-script
        python3 hello/manage.py runserver
